In [1]:
a = [[1,2], [2,2], [3,3], [1,3], [2,4]]

In [1]:
import torch

In [11]:
depth = 3
hierarchy = 1

a = [torch.tensor([]) for h in range(depth+1)]

b = torch.tensor([3., 4.])

a[hierarchy] = torch.cat([a[hierarchy], b], dim=0)

print(a)
print(b)


[tensor([]), tensor([3., 4.]), tensor([]), tensor([])]
tensor([3., 4.])


In [12]:
a = torch.tensor([[1., 2., 3., 4., 5., 6.,]])

In [7]:
p, a = a.max(dim=1)
print(p)
print(a)

tensor([6.])
tensor([5])


In [5]:
l = []
m = []
for d in a:
    l.append(d[0])
    m.append(d[1])
    
print(l)
print(m)


[1, 2, 3, 1, 2]
[2, 2, 3, 3, 4]


In [8]:
len(torch.tensor([]))

0

In [14]:
a = torch.zeros(6)
b = torch.tensor([1,2,1,4,2,0])

a[b] += 1
print(a)

tensor([1., 1., 1., 0., 1., 0.])


In [9]:
import torch

a = torch.arange(10)
print(a)

a[[2,3,4]]
print(a**2)


b = torch.tensor([[2,3,4], [5,6,7], [8,9,10]])
print(b)
print(b[:, torch.tensor([1])])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])
tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])
tensor([[3],
        [6],
        [9]])
